[tool.poetry]
name = "metricity"
version = "0.1.0"
description = "Advanced metric collection for the Python Discord server"
authors = ["Joe Banks <joseph@josephbanks.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "^1.4.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
flake8-annotations = "^2.3.0"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
