name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  push_docker_image:
    name: Build & Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile -t python-discord/metricity/metricity:${{ github.sha }}

      - name: Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: python-discord/metricity/metricity:${{ github.sha }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
